/**
 * Centralized English strings for the Admin Console (Console Tier).
 * Following design.md specifications: Admin panel is single-language English,
 * and strings live in a dedicated constants file for maintainability.
 */

export const STRINGS = {
  common: {
    appName: 'autopartdz',
    adminConsole: 'Admin Console',
    loading: 'Loading…',
    save: 'Save',
    saving: 'Saving…',
    create: 'Create',
    creating: 'Creating…',
    cancel: 'Cancel',
    edit: 'Edit',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    search: 'Search…',
    noRecords: 'No records found.',
    actions: 'Actions',
    status: 'Status',
    filterByStatus: 'Filter by status:',
    requiredIndicator: '*',
    back: 'Back',
    signOut: 'Sign out',
    serverError: 'A server error occurred. Please try again.',
  },
  docTypes: {
    title: 'Document Types',
    subtitle: 'Manage the official import documents catalog, pricing tiers, and sourcing defaults.',
    createNew: '+ New Document Type',
    editTitle: 'Edit Document Type',
    createTitle: 'Create Document Type',
    code: 'Code',
    codePlaceholder: 'e.g. COC, CO, CI',
    codeHint: 'Uppercase code (e.g. COC). Optional, but unique and immutable once saved.',
    codeImmutableNote: 'Code cannot be altered or removed once set.',
    shortName: 'Short Name',
    shortNamePlaceholder: 'e.g. Certificate of Conformity',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Official full title in French or English',
    slug: 'Slug',
    slugPlaceholder: 'Auto-generated from short name if blank',
    slugHint: 'URL-friendly unique identifier.',
    category: 'Category',
    categoryPlaceholder: 'e.g. Customs, Technical, Transport',
    categoryHint: 'Type to select or add a new category.',
    originLanguage: 'Origin Language',
    originLanguagePlaceholder: 'e.g. Chinese, English, French',
    defaultSource: 'Default Source',
    sourceLocal: 'Local (Algeria office)',
    sourceChina: 'China (Supplier / Partner)',
    turnaround: 'Est. Turnaround (Days)',
    turnaroundPlaceholder: 'e.g. 5',
    sortOrder: 'Sort Order',
    description: 'Description / Notes',
    descriptionPlaceholder: 'Internal notes or filing guidelines for this document…',
    hasTranslation: 'Requires / Offers Chinese Translation',
    hasTranslationHint: 'When checked, translation-specific pricing tiers must be configured.',
    pricingSection: 'Pricing Configuration (DZD)',
    pricingOriginalOnly: 'Original Only (Standard)',
    pricingWithTranslation: 'Original + Translation',
    pricingTranslationOnly: 'Translation Only',
    clientPrice: 'Client Price (DZD)',
    costPrice: 'Cost Price (DZD)',
    imageSection: 'Example Document Image',
    uploadImage: 'Upload example image',
    replaceImage: 'Replace image',
    noImageYet: 'No sample image uploaded yet.',
    activeToggleConfirm: 'Are you sure you want to toggle status?',
  },
  carCategories: {
    title: 'Car Categories',
    subtitle: 'Define car categories and the set of required official documents for customs clearance.',
    createNew: '+ New Car Category',
    editTitle: 'Edit Car Category',
    createTitle: 'Create Car Category',
    name: 'Category Name',
    namePlaceholder: 'e.g. Passenger Vehicles (M1), Commercial (N1), Electric',
    description: 'Description',
    descriptionPlaceholder: 'Customs classification notes, engine limits, vehicle types…',
    requiredDocs: 'Required Document Types',
    requiredDocsHint: 'Check all documents required when importing this category of vehicle.',
    noDocsAvailable: 'No active document types available to select.',
    docCount: 'Required Documents',
  },
};
